name: r2d2
version: 0.1.1
author: Joris Hermans <hermansj@gmail.com>
description: A modern device detection package
homepage: https://github.com/ForceUniverse/r2d2
dependencies:
  http: '>=0.11.2 <0.12.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.12.0'
dev_dependencies:
  test: '>=0.12.1 <0.13.0'
