name: r2d2
version: 0.1.0
author: Joris Hermans <hermansj@gmail.com>
description: A modern device detection package
homepage: https://github.com/ForceUniverse/r2d2
dependencies:
  http: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.9.1'